"""Provision the AMI fleet entities on TB *Central* (not the Edge) and
assign them to the edge-r1000-wm6108 Edge instance so Central pushes
them down via gRPC cloud sync.

When the R1000 Edge runs in cloud-attached mode (CLOUD_ROUTING_KEY set
to the routing key of a registered Edge in Central), Central is the
source of truth for all entities. Anything created directly on the Edge
collides with what Central pushes (duplicate-key constraint errors on
sync). The correct workflow: create everything on Central, assign it to
the Edge, Central pushes it down on the next sync tick.

What it does:
  1. Re-uses the LwM2M XMLs already generated by tools/tb_edge_upload_models.py
     (./models/*.xml) and uploads them as LWM2M_MODEL resources on Central.
  2. Re-uses build_profile_body() from tb_edge_provision.py to create the
     AMI_LwM2M_Node device profile, then appends the 4 AMI alarm rules
     from tb_edge_monitoring_setup.py.build_ami_alarms() so alarms ship
     down WITH the profile in one sync.
  3. Creates the 7 ami-esp32c6-XXXX devices with LwM2M NoSec credentials.
  4. Builds and creates the AMI Fleet Health dashboard.
  5. Assigns every resource/profile/device/dashboard to the Edge in
     Central. Edge receives them on next cloud-sync tick.

Skipped here (cleaner to add post-sync once Edge has the default chain):
  - Rule-chain Device Profile-node insertion (would target the EDGE-type
    template rule chain on Central; needs to be done on the chain that's
    already assigned to this Edge).
  - Notification template/rule (those are Central-scoped, not synced).

Idempotent: re-running matches existing entities by name/title and
updates them in place; edge assignment is a POST that's safe to repeat.

Usage:
    python tools/tb_central_provision.py
    python tools/tb_central_provision.py --dry-run
    python tools/tb_central_provision.py --edge-name edge-r1000-wm6108
"""
from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

import fleet_common as fc
fc.bootstrap_venv()
import requests  # noqa: E402

# Import the reusable bits from the existing scripts.
sys.path.insert(0, str(Path(__file__).parent))
import tb_edge_provision as prov         # noqa: E402
import tb_edge_monitoring_setup as mon   # noqa: E402

CENTRAL_HOST = "192.168.8.124"
CENTRAL_PORT = 8080
CENTRAL_USER = "tenant@thingsboard.org"
CENTRAL_PASS = "tenant"
DEFAULT_EDGE_NAME = "edge-r1000-wm6108"

MODELS_DIR = Path(__file__).resolve().parent.parent / "models"

PROFILE_NAME = prov.PROFILE_NAME
ALL_NODES = prov.ALL_NODES
EP = prov.EP


class TB:
    def __init__(self, base, user, password):
        self.base = base.rstrip("/")
        self.s = requests.Session()
        r = self.s.post(f"{self.base}/api/auth/login",
                        json={"username": user, "password": password}, timeout=15)
        r.raise_for_status()
        self.s.headers.update({"Authorization": f"Bearer {r.json()['token']}",
                               "Content-Type": "application/json"})

    def get(self, path):
        r = self.s.get(f"{self.base}{path}", timeout=20)
        r.raise_for_status()
        return r.json()

    def post(self, path, body=None):
        kw = {"timeout": 30}
        if body is not None:
            kw["data"] = json.dumps(body)
        r = self.s.post(f"{self.base}{path}", **kw)
        if not r.ok:
            raise RuntimeError(f"POST {path} -> {r.status_code}: {r.text[:400]}")
        return r.json() if r.text else {}


def resolve_edge(tb: TB, name: str) -> str:
    edges = tb.get("/api/tenant/edges?pageSize=200&page=0")["data"]
    e = next((x for x in edges if x["name"] == name), None)
    if not e:
        raise SystemExit(f"Edge '{name}' not found in Central. "
                         f"Existing: {[x['name'] for x in edges]}")
    print(f"[edge] target: {name}  id={e['id']['id']}  routingKey={e.get('routingKey','?')}")
    return e["id"]["id"]


def normalize_edge_lwm2m_keys(dry: bool) -> None:
    """Force resource_key on the Edge's LWM2M_MODEL resources to the canonical
    `{objectId}_{version}` form (e.g. `10242_1.0`) so Leshan's
    LwM2mVersionedModelProvider can find them.

    Cloud sync from Central pushes LWM2M_MODEL resources to the Edge with a
    random-prefixed resource_key (e.g. `DAOUZALUTzTUvcV_10242_1.0`) intended
    for cross-tenant uniqueness. Leshan looks up by the bare key and silently
    drops every observe-notify with "Tenant hasn't such the resource: Object
    model with id [10242] version [1.0]" — visible in tb-edge logs, invisible
    in the UI (devices register, telemetry just stays at the 33000-only set).

    The fix is one UPDATE per resource — derive the canonical key from the
    file_name (which we always write as `{objectId}.xml`) and the title
    suffix (which we always write as `... v{version}`).

    Note: requires SSH access to the Edge host because there's no REST API
    to set resource_key directly on TB Edge CE.
    """
    import re, paramiko  # paramiko is already in REQUIRED_PYTHON_DEPS
    # Map fileName -> canonical key derived from our model titles.
    # Keep this list aligned with the upload_model() calls in main().
    canonical = {
        "10242.xml": "10242_1.0",
        "33000.xml": "33000_1.0",   # rolled 2.4 -> 2.2 (post-mortem opaque path)
        "3303.xml":  "3303_1.1",
    }
    if dry:
        print(f"[edge-keys] would normalize: {canonical}")
        return
    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect("192.168.8.111", username="root", password="root", timeout=15)
    try:
        sql = "".join(
            f"UPDATE resource SET resource_key='{k}' "
            f"WHERE resource_type='LWM2M_MODEL' AND file_name='{fn}' "
            f"AND resource_key <> '{k}';\n"
            for fn, k in canonical.items()
        )
        cmd = ("docker exec -i tb-edge-postgres psql -U postgres -d thingsboard_edge -tA "
               "-c \"" + sql.replace('"', '\\"').replace("\n", " ") + "\"")
        _, o, e = c.exec_command(cmd, timeout=30)
        out, err = o.read().decode(), e.read().decode()
        rc = o.channel.recv_exit_status()
        # Count UPDATEs
        updates = re.findall(r"UPDATE\s+(\d+)", out)
        changed = sum(int(n) for n in updates)
        print(f"[edge-keys] normalized {changed} LWM2M_MODEL resource_key(s) on Edge "
              f"(restart tb-edge-v2 for Leshan to reload if any changed)")
        if rc != 0 and err.strip():
            print(f"[edge-keys] WARN: {err.strip()[:200]}")
    finally:
        c.close()


def upload_model(tb: TB, title: str, filename: str, xml: str, dry: bool) -> str:
    # LWM2M_MODEL resources are immutable on TB: POST with an existing id
    # returns 400 "This type of resource can't be updated". So: keep the
    # existing one as-is (idempotent) or create when absent.
    existing = tb.get("/api/resource?pageSize=500&page=0").get("data", [])
    match = next((r for r in existing
                  if r.get("title") == title or r.get("fileName") == filename), None)
    if match:
        print(f"[model] {title:40s} exists (immutable)")
        return match["id"]["id"]
    print(f"[model] {title:40s} create")
    if dry:
        return "<dry-run>"
    body = {
        "resourceType": "LWM2M_MODEL",
        "title": title,
        "fileName": filename,
        "data": base64.b64encode(xml.encode()).decode(),
    }
    res = tb.post("/api/resource", body)
    return res["id"]["id"]


def assign_resource(tb: TB, edge_id: str, kind: str, entity_id: str,
                    name: str, dry: bool):
    """Assign an entity to a specific Edge so Central pushes it down.

    In TB CE only some entity types support per-Edge assignment via this
    endpoint family — `device`, `dashboard`, `ruleChain`, `asset`. Other
    tenant-scoped entities (LwM2M MODEL resources, deviceProfiles) are
    auto-synced to every Edge of the tenant; calling the assign endpoint
    on them returns 404 ("No static resource") and is unnecessary.
    """
    AUTO_SYNC = {"resource", "deviceProfile"}
    if kind in AUTO_SYNC:
        print(f"          (auto-synced via tenant): {name}")
        return
    if dry:
        print(f"          assign-to-edge[{kind}] {name}  (dry-run)")
        return
    try:
        tb.post(f"/api/edge/{edge_id}/{kind}/{entity_id}")
        print(f"          assigned to edge[{kind}]: {name}")
    except RuntimeError as e:
        if "already" in str(e).lower():
            print(f"          already assigned[{kind}]: {name}")
        else:
            raise


def apply_profile_with_alarms(tb: TB, dry: bool) -> str:
    body = prov.build_profile_body()
    # bake the AMI alarms into the profile so they sync down with it
    body["profileData"]["alarms"] = mon.build_ami_alarms()

    profiles = tb.get("/api/deviceProfiles?pageSize=100&page=0")["data"]
    existing = next((p for p in profiles if p["name"] == PROFILE_NAME), None)
    if existing:
        full = tb.get(f"/api/deviceProfile/{existing['id']['id']}")
        body["id"] = full["id"]
        action = "update"
    else:
        action = "create"
    print(f"[profile] '{PROFILE_NAME}': {action}  "
          f"(LWM2M, {len(prov.OBSERVE)} observed / {len(prov.TELEMETRY)} telemetry keys, "
          f"+ {len(body['profileData']['alarms'])} alarm rules baked in)")
    for a in body["profileData"]["alarms"]:
        sev = next(iter(a["createRules"]))
        print(f"          + alarm {a['alarmType']:16s} [{sev}]")
    if dry:
        return existing["id"]["id"] if existing else "<dry-run>"
    res = tb.post("/api/deviceProfile", body)
    pid = res["id"]["id"]
    print(f"[profile] OK  id={pid}")
    return pid


def provision_device(tb: TB, endpoint: str, profile_id: str, dry: bool) -> str:
    found = tb.get(f"/api/tenant/deviceInfos?pageSize=100&page=0&textSearch={endpoint}")["data"]
    dev = next((d for d in found if d["name"] == endpoint), None)
    if dev:
        dev_id = dev["id"]["id"]
        state = "exists"
    else:
        state = "create"
    print(f"[device]  {endpoint:22s} {state}", end="")
    if dry:
        print("  (dry-run)")
        return dev_id if dev else "<dry-run>"
    if not dev:
        dev = tb.post("/api/device", {
            "name": endpoint, "label": endpoint,
            "deviceProfileId": {"entityType": "DEVICE_PROFILE", "id": profile_id},
        })
        dev_id = dev["id"]["id"]
    creds_value = json.dumps({
        "client": {"securityConfigClientMode": "NO_SEC", "endpoint": endpoint},
        "bootstrap": {
            "bootstrapServer": {"securityMode": "NO_SEC"},
            "lwm2mServer": {"securityMode": "NO_SEC"},
        },
    })
    existing_creds = tb.get(f"/api/device/{dev_id}/credentials")
    tb.post("/api/device/credentials", {
        "id": existing_creds.get("id"),
        "deviceId": {"entityType": "DEVICE", "id": dev_id},
        "credentialsType": "LWM2M_CREDENTIALS",
        "credentialsId": endpoint,
        "credentialsValue": creds_value,
    })
    print("  -> LWM2M / NO_SEC creds set OK")
    return dev_id


def apply_dashboard(tb: TB, dry: bool) -> str:
    dash_body = mon.build_dashboard()
    existing = tb.get("/api/tenant/dashboards?pageSize=200&page=0")["data"]
    match = next((d for d in existing if d.get("title") == dash_body["title"]
                  or d.get("name") == dash_body["title"]), None)
    if match:
        dash_body["id"] = match["id"]
        action = "update"
    else:
        action = "create"
    print(f"[dash] '{dash_body['title']}': {action}")
    if dry:
        return match["id"]["id"] if match else "<dry-run>"
    res = tb.post("/api/dashboard", dash_body)
    print(f"[dash] OK  id={res['id']['id']}")
    return res["id"]["id"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default=CENTRAL_HOST)
    ap.add_argument("--port", type=int, default=CENTRAL_PORT)
    ap.add_argument("--user", default=CENTRAL_USER)
    ap.add_argument("--password", default=CENTRAL_PASS)
    ap.add_argument("--edge-name", default=DEFAULT_EDGE_NAME)
    ap.add_argument("--nodes", default=",".join(ALL_NODES))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    base = f"http://{args.host}:{args.port}"
    nodes = [n.strip() for n in args.nodes.split(",") if n.strip()]
    print(f"=== TB Central provision -> {base}   target edge: {args.edge_name} ===")
    print(f"    profile: {PROFILE_NAME}   nodes: {nodes}")
    if args.dry_run:
        print("    (DRY RUN — no changes)")

    tb = TB(base, args.user, args.password)
    edge_id = resolve_edge(tb, args.edge_name)

    # ── 1) LwM2M models ──
    models = [
        ("Object 10242 v1.0 - 3-Phase Power Meter", "10242.xml"),
        ("Object 33000 v2.2 - Thread + LwM2M Diag", "33000.xml"),
        ("Object 3303 v1.1 - IPSO Temperature",    "3303.xml"),
    ]
    for title, fname in models:
        path = MODELS_DIR / fname
        if not path.exists():
            raise SystemExit(f"missing {path}; run tools/tb_edge_upload_models.py --dry-run first")
        xml = path.read_text(encoding="utf-8")
        rid = upload_model(tb, title, fname, xml, args.dry_run)
        assign_resource(tb, edge_id, "resource", rid, title, args.dry_run)

    # ── 2) device profile + baked-in alarms ──
    pid = apply_profile_with_alarms(tb, args.dry_run)
    assign_resource(tb, edge_id, "deviceProfile", pid, PROFILE_NAME, args.dry_run)

    # ── 3) 7 devices ──
    for suffix in nodes:
        endpoint = EP.format(suffix)
        did = provision_device(tb, endpoint, pid, args.dry_run)
        assign_resource(tb, edge_id, "device", did, endpoint, args.dry_run)

    # ── 4) dashboard ──
    did = apply_dashboard(tb, args.dry_run)
    assign_resource(tb, edge_id, "dashboard", did, "AMI Fleet Health", args.dry_run)

    # Post-sync fix: the cloud sync gives LWM2M_MODEL resources a random-
    # prefixed resource_key on the Edge, which breaks Leshan's model lookup.
    # Normalize directly via SSH+SQL. If anything changed, the user must
    # `docker restart tb-edge-v2` for Leshan to re-pick up the model file.
    normalize_edge_lwm2m_keys(args.dry_run)

    print("=== done — Central will push these entities to the Edge on the next "
          "sync tick (usually within seconds). Watch the Edge with:")
    print("    docker logs tb-edge-v2 --tail 50 -f")
    print("If meter/temperature keys never appear on new devices, run:")
    print("    ssh root@192.168.8.111 docker restart tb-edge-v2")
    print("(needed only once after a fresh sync to reload LwM2M models into Leshan)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
